### ISSUE TITLE
Drop dependency on `laminas-cache-storage-adapter-apcu`?

### ISSUE THREAD

**Issue by Ocramius** [laminas/laminas-cache-storage-adapter-test#43]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Taken from https://github.com/laminas/laminas-cache-storage-adapter-test/pull/42

As discussed there, `apcu` (as well as other extensions) will always lag back a bit: we may want to drop the hard dependency, and instead test this test rig with a different adapter by default.

**Comment by boesing** [comment]
I moved integration tests to dedicated CI jobs in #49, so we can actually have this component unit tested while integration tests can be handled dedicatedly.
Thus, we can explicitly allow APCu integration test fails in case we need it. I'd still prefer to keep it as from what I've seen in the last years, APCu was one of the first extensions being compatible with newer PHP versions and thus that might still be useful.

Would that solve this issue?
